apiVersion: apps/v1
kind: Deployment
metadata:
  name: adminer
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: adminer
  template:
    metadata:
      name: adminer
      labels:
        app.kubernetes.io/name: adminer
    spec:
      containers:
        - name: adminer
          image: adminer
          resources:
            requests:
              memory: "14Mi"
              cpu: "30m"
            limits:
              memory: "18Mi"
              cpu: "500m"
---
kind: Service
apiVersion: v1
metadata:
  labels:
    app: adminer
  name: adminer
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: adminer
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      nodePort: 31080