apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: rabbitmq
  template:
    metadata:
      name: rabbitmq
      labels:
        app.kubernetes.io/name: rabbitmq
    spec:
      containers:
        - name: rabbitmq 
          image: rabbitmq:management-alpine
          resources:
            requests:
              memory: "1Gi"
              cpu: "100m"
            limits:
              memory: "1.5Gi"
              cpu: "2000m"
---
kind: Service
apiVersion: v1
metadata:
  labels:
    app: rabbitmq
  name: rabbitmq
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: rabbitmq
  ports:
    - name: rabbitmq
      port: 5672
      targetPort: 5672
      nodePort: 30567
    - name: http
      port: 15672
      targetPort: 15672
      nodePort: 32080
